DELHI_POLICE_STATIONS = ['adarsh nagar', 'alipur', 'aman vihar', 'amar colony',
       'anand parbat', 'anand vihar', 'ashok vihar', 'baba haridas nagar',
       'badarpur', 'bara hindu rao', 'barakhamba road', 'bawana',
       'begumpur', 'bhajanpura', 'bhalswa dairy', 'bharat nagar',
       'bindapur', 'burari', 'chanakyapuri', 'chandni mahal', 'chhawla',
       'chitranjan park (cr park)', 'civil lines', 'connaught place',
       'dabri', 'daryaganj', 'db gupta road', 'defence colony',
       'delhi cantt', 'dwarka north', 'dwarka sector-23', 'dwarka south',
       'farsh bazar', 'fatehpur beri', 'gandhi nagar', 'geeta colony',
       'ghazipur', 'gokalpuri', 'govindpuri', 'greater kailash',
       'gtb enclave', 'gulabi bagh', 'h. n. din', 'hari nagar',
       'harsh vihar', 'hauz khas', 'hauz qazi', 'i.p. estate',
       'inderpuri', 'jaffarpur kalan', 'jafrabad', 'jagatpuri',
       'jahangirpuri', 'jama masjid', 'jamia nagar', 'janakpuri',
       'jyoti nagar', 'kalkaji', 'kalyanpuri', 'kamla market',
       'kanjhawala', 'kapashera', 'karawal nagar', 'karol bagh',
       'kashmere gate', 'keshav puram', 'khajuri khas', 'khyala',
       'kirti nagar', 'kn katju marg', 'kotla mubarakpur',
       'krishna nagar', 'lahori gate', 'lajpat nagar', 'lodhi colony',
       'madhu vihar', 'mahendra park', 'malviya nagar', 'mandawali',
       'mandir marg', 'mangolpuri', 'mansarovar park', 'maurice nagar',
       'maurya enclave', 'mayapuri', 'mayur vihar', 'mehrauli',
       'mianwali nagar', 'model town', 'moti nagar', 'mukherjee nagar',
       'mundka', 'nabi karim', 'najafgarh', 'nand nagri', 'nangloi',
       'naraina', 'narela', 'neb sarai', 'new ashok nagar',
       'new friends colony', 'new usmanpur', 'nihal vihar',
       'okhla industrial area', 'pahar ganj', 'palam village',
       'pandav nagar', 'parliament street', 'paschim vihar',
       'patel nagar', 'prasad nagar', 'prashant vihar', 'preet vihar',
       'pul prahladpur', 'punjabi bagh', 'rajinder nagar',
       'rajouri garden', 'ranhola', 'rani bagh', 'ranjeet nagar',
       'rohini north', 'rohini south', 'roop nagar', 'sadar bazar',
       'safdarjung enclave', 'sagarpur', 'saket', 'samaypur badli',
       'sangam vihar', 'sarai rohilla', 'sarita vihar', 'sarojini nagar',
       'seelampur', 'seemapuri', 'shahbad dairy', 'shahdara', 'shakarpur',
       'shalimar bagh', 'sonia vihar', 'south campus', 'subhash place',
       'subzi mandi', 'sultanpuri', 'sunlight colony', 'swaroop nagar',
       'tilak marg', 'tilak nagar', 'timarpur', 'tughlak road',
       'uttam nagar', 'vasant kunj north', 'vasant kunj south',
       'vasant vihar', 'vijay vihar', 'vikaspuri', 'vivek vihar',
       'welcome']